dunderToSlot = {
    "__repr__": "[tp$repr](): pyStr",
    "__str__": "[tp$str](): pyStr",
    "__init__": "[tp$init](args: Args, kws?: Kwargs): void",
    "__new__": "[tp$new](args: Args, kws?: Kwargs): {}",
    "__hash__": "[tp$hash()]: number",
    "__call__": "[tp$call](args: Args, kws?: Kwargs): {}",
    "__iter__": "[Symbol.iterator](): {}Iterator",
    "__next__": "next(): IteratorResult<pyObject, pyObject> ",

    "__eq__": "[tp$richcompare](other: pyObject, op: richCompareOp): boolean | pyNotImplemented",
    "__ne__": None,
    "__lt__": None,
    "__le__": None,
    "__gt__": None,
    "__ge__": None,

    "__abs__": "[nb$abs](): {}",
    "__neg__": "[nb$neg](): {}",
    "__pos__": "[nb$pos](): {}",
    "__int__": "[nb$int](): pyInt",
    "__float__": "[nb$float](): pyFloat",

    "__add__": "[nb$add](other: pyObject): {}",
    "__radd__": "[nb$radd](other: pyObject): {}",
    "__iadd__": "[nb$iadd](other: pyObject): {}",
    "__sub__": "[nb$sub](other: pyObject): {}",
    "__rsub__": "[nb$rsub](other: pyObject): {}",
    "__isub__": "[nb$isub](other: pyObject): {}",
    "__mul__": "[nb$mul](other: pyObject): {}",
    "__rmul__": "[nb$rmul](other: pyObject): {}",
    "__imul__": "[nb$imul](other: pyObject): {}",
    "__truediv__": "[nb$div](other: pyObject): {}",
    "__rtruediv__": "[nb$rdiv](other: pyObject): {}",
    "__itruediv__": "[nb$idiv](other: pyObject): {}",
    "__floordiv__": "[nb$floordiv](other: pyObject): {}",
    "__rfloordiv__": "[nb$rfloordiv](other: pyObject): {}",
    "__ifloordiv__": "[nb$ifloordiv](other: pyObject): {}",
    "__invert__": "[nb$invert](other: pyObject): {}",
    "__mod__": "[nb$mod](other: pyObject): {}",
    "__rmod__": "[nb$rmod](other: pyObject): {}",
    "__imod__": "[nb$imod](other: pyObject): {}",
    "__divmod__": "[nb$divmod](other: pyObject): {}",
    "__rdivmod__": "[nb$rdivmod](other: pyObject): {}",
    "__pow__": "[nb$pow](other: pyObject, mod?: pyObject): {}",
    "__rpow__": "[nb$rpow](other: pyObject, mod? pyObject): {}",
    "__ipow__": "[nb$ipow]",

    "__bool__": "[nb$bool](): boolean",
    "__long__": "[nb$long]",

    "__lshift__": "[nb$lshift](other: pyObject): {}",
    "__rlshift__": "[nb$rlshift](other: pyObject): {}",
    "__ilshift__": "[nb$ilshift](other: pyObject): {}",
    "__rshift__": "[nb$rshift](other: pyObject): {}",
    "__rrshift__": "[nb$rrshift](other: pyObject): {}",
    "__irshift__": "[nb$irshift](other: pyObject): {}",

    "__and__": "[nb$and](other: pyObject): {}",
    "__rand__": "[nb$rand](other: pyObject): {}",
    "__iand__": "[nb$iand](other: pyObject): {}",
    "__or__": "[nb$or](other: pyObject): {}",
    "__ror__": "[nb$ror](other: pyObject): {}",
    "__ior__": "[nb$ior](other: pyObject): {}",
    "__xor__": "[nb$xor](other: pyObject): {}",
    "__rxor__": "[nb$rxor](other: pyObject): {}",
    "__ixor__": "[nb$ixor](other: pyObject): {}",

    "__matmul__": "[nb$matmul](other: pyObject): {}",
    "__rmatmul__": "[nb$rmatmul](other: pyObject): {}",
    "__imatmul__": "[nb$imatmul](other: pyObject): {}",

    "__get__": "[tp$descr_get](obj: pyObject, type?: pyObject): pyObject",
    "__set__": "[tp$descr_set](obj: pyObject, val?: pyObject): void",
    "__delete__": None,

    "__getattribute__": "[tp$getattr]",
    "__getattr__": None,
    "__setattr__": "[tp$setattr]",
    "__delattr__": None,

    "__len__": "[sq$len](): number",
    "__contains__": "[sq$contains](item: pyObject): boolean",
    "__getitem__": "[mp$subscript](item: pyObject): pyObject",
    "__setitem__": "[mp$ass_subscript](item: pyObject, val?: pyObject): void",
    "__delitem__": None,
dunderToSlot = {
    "__repr__": "[tp$repr](): pyStr",
    "__str__": "[tp$str](): pyStr",
    "__init__": "[tp$init](args: Args, kws?: Kwargs): void",
    "__new__": "[tp$new](args: Args, kws?: Kwargs): {}",
    "__hash__": "[tp$hash()]: number",
    "__call__": "[tp$call](args: Args, kws?: Kwargs): {}",
    "__iter__": "[Symbol.iterator](): {}Iterator",
    "__next__": "next(): IteratorResult<pyObject, pyObject> ",

    "__eq__": "[tp$richcompare](other: pyObject, op: richCompareOp): boolean | pyNotImplemented",
    "__ne__": None,
    "__lt__": None,
    "__le__": None,
    "__gt__": None,
    "__ge__": None,

    "__abs__": "[nb$abs](): {}",
    "__neg__": "[nb$neg](): {}",
    "__pos__": "[nb$pos](): {}",
    "__int__": "[nb$int](): pyInt",
    "__float__": "[nb$float](): pyFloat",

    "__add__": "[nb$add](other: pyObject): {}",
    "__radd__": "[nb$radd](other: pyObject): {}",
    "__iadd__": "[nb$iadd](other: pyObject): {}",
    "__sub__": "[nb$sub](other: pyObject): {}",
    "__rsub__": "[nb$rsub](other: pyObject): {}",
    "__isub__": "[nb$isub](other: pyObject): {}",
    "__mul__": "[nb$mul](other: pyObject): {}",
    "__rmul__": "[nb$rmul](other: pyObject): {}",
    "__imul__": "[nb$imul](other: pyObject): {}",
    "__truediv__": "[nb$div](other: pyObject): {}",
    "__rtruediv__": "[nb$rdiv](other: pyObject): {}",
    "__itruediv__": "[nb$idiv](other: pyObject): {}",
    "__floordiv__": "[nb$floordiv](other: pyObject): {}",
    "__rfloordiv__": "[nb$rfloordiv](other: pyObject): {}",
    "__ifloordiv__": "[nb$ifloordiv](other: pyObject): {}",
    "__invert__": "[nb$invert](other: pyObject): {}",
    "__mod__": "[nb$mod](other: pyObject): {}",
    "__rmod__": "[nb$rmod](other: pyObject): {}",
    "__imod__": "[nb$imod](other: pyObject): {}",
    "__divmod__": "[nb$divmod](other: pyObject): {}",
    "__rdivmod__": "[nb$rdivmod](other: pyObject): {}",
    "__pow__": "[nb$pow](other: pyObject, mod?: pyObject): {}",
    "__rpow__": "[nb$rpow](other: pyObject, mod? pyObject): {}",
    "__ipow__": "[nb$ipow]",

    "__bool__": "[nb$bool](): boolean",
    "__long__": "[nb$long]",

    "__lshift__": "[nb$lshift](other: pyObject): {}",
    "__rlshift__": "[nb$rlshift](other: pyObject): {}",
    "__ilshift__": "[nb$ilshift](other: pyObject): {}",
    "__rshift__": "[nb$rshift](other: pyObject): {}",
    "__rrshift__": "[nb$rrshift](other: pyObject): {}",
    "__irshift__": "[nb$irshift](other: pyObject): {}",

    "__and__": "[nb$and](other: pyObject): {}",
    "__rand__": "[nb$rand](other: pyObject): {}",
    "__iand__": "[nb$iand](other: pyObject): {}",
    "__or__": "[nb$or](other: pyObject): {}",
    "__ror__": "[nb$ror](other: pyObject): {}",
    "__ior__": "[nb$ior](other: pyObject): {}",
    "__xor__": "[nb$xor](other: pyObject): {}",
    "__rxor__": "[nb$rxor](other: pyObject): {}",
    "__ixor__": "[nb$ixor](other: pyObject): {}",

    "__matmul__": "[nb$matmul](other: pyObject): {}",
    "__rmatmul__": "[nb$rmatmul](other: pyObject): {}",
    "__imatmul__": "[nb$imatmul](other: pyObject): {}",

    "__get__": "[tp$descr_get](obj: pyObject, type?: pyObject): pyObject",
    "__set__": "[tp$descr_set](obj: pyObject, val?: pyObject): void",
    "__delete__": None,

    "__getattribute__": "[tp$getattr]",
    "__getattr__": None,
    "__setattr__": "[tp$setattr]",
    "__delattr__": None,

    "__len__": "[sq$len](): number",
    "__contains__": "[sq$contains](item: pyObject): boolean",
    "__getitem__": "[mp$subscript](item: pyObject): pyObject",
    "__setitem__": "[mp$ass_subscript](item: pyObject, val?: pyObject): void",
    "__delitem__": None,
}}